### ISSUE TITLE
Possible compatibility error of the envoy api version3 on dispatch_http_call.

### ISSUE THREAD

**Issue by Fr0zenBoy** [proxy-wasm/proxy-wasm-rust-sdk#122]
#Summary:
 
 I'm trying to run a validation that needs to hit an external service in this case s3, the problem is that regardless of my configuration or following the examples given here, nothing works and I always get the same error:
 
 ```log
 "Cannot dispatch call to s3: BadArgument"
 ```
 
 this is my setting on envoy.yaml:
 ```yaml
 static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 1443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          server_name: static-cluster
          stat_prefix: ingress_http
          # Certificate will be forwarded in PEM format within x-forwarded-client-cert header
          forward_client_cert_details: SANITIZE_SET
          set_current_client_cert_details:
            subject: true
            cert: true
          access_log:
            name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: ./envoy.log
          route_config:
            name: search_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: s3
                  auto_host_rewrite: true
              
          http_filters:
          - name: envoy.filters.http.wasm
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              config:
                name: "poc-envoy"
                root_id: "poc-envoy"
                configuration:
                  "@type": "type.googleapis.com/google.protobuf.StringValue"
                  value: |
                    {"country": "br",
                     "environment": "staging",
                     "snapshot_bucket": "nu-crl-snapshot",
                     "delta_bucket": "snapshot_metadata.json",
                     "delta_interval_seconds": 10}
                vm_config:
                  runtime: "envoy.wasm.runtime.v8"
                  vm_id: "poc-envoy"
                  code:
                    local:
                      filename: "/Users/thiago.conceicao/projects/envoy-crl-filter/target/wasm32-unknown-unknown/release/poc_envoy.wasm"
          - name: envoy.filters.http.router
            typed_config: {}
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          require_client_certificate: true
          common_tls_context:
            validation_context:
              trusted_ca:
                filename: dump/root/rootCA.crt
              crl:
                filename: dump/crl/crl.pem
            tls_params:
              tls_minimum_protocol_version: TLSv1_2
            tls_certificates:
              certificate_chain:
                filename: dump/generated_certs/server_cert.crt
              private_key:
                filename: dump/request/iota_csr_key.key

  clusters:
    - name: s3
      connect_timeout: 5s
      type: logical_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: s3
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: nu-keysets-br-staging.s3.amazonaws.com
                  port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: nu-keysets-br-staging.s3.amazonaws.com

 ```
 
 this is an example of my code:
 
 ```rust
struct ExternalRequest;

impl wasm::traits::Context for ExternalRequest {}
impl wasm::traits::HttpContext for ExternalRequest {
    fn on_http_request_headers(&mut self, _: usize) -> wasm::types::Action {
        let secret: &str = &make_authorization_header();
        let upstream: &str = "s3";
        let headers: Vec<(&str, &str)> = vec![];
        let trailers: Vec<(&str, &str)> = vec![];
        let timeout: Duration = Duration::from_secs(5);
        let request = self.dispatch_http_call(upstream, headers, None, trailers, timeout);

        match request {
            Err(e) => {
                error!("Cannot dispatch call to cluster A: {:?}", e);
            }

            Ok(_) => {
                info!("Call to cluster s3 dispatched");
            }
        }

        wasm::types::Action::Pause
    }
}
 ```
 
 I thought this might be my configuration error, but running the examples in this [repository](https://github.com/proxy-wasm/proxy-wasm-rust-sdk) I got this error:
 ```log
 [2021-09-01 10:58:45.817][28718][info][main] [source/server/server.cc:855] exiting
The v2 xDS major version is deprecated and disabled by default. Support for v2 will be removed from Envoy at the start of Q1 2021. You may make use of v2 in Q4 2020 by following the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/transition. (Unknown field in: {"static_resources":{"listeners":[{"address":{"socket_address":{"port_value":8888,"address":"0.0.0.0"}},"name":"main","filter_chains":[{"filters":[{"name":"envoy.http_connection_manager","config":{"http_filters":[{"name":"envoy.filters.http.wasm","config":{"config":{"vm_config":{"vm_id":"test_vm","runtime":"envoy.wasm.runtime.v8","code":{"local":{"filename":"target/wasm32-unknown-unknown/release/rust_wasm_filter.wasm"}}},"name":"test_wasm_plugin"}}},{"config":{},"name":"envoy.router"}],"codec_type":"auto","stat_prefix":"ingress_http","route_config":{"name":"local_route","virtual_hosts":[{"routes":[{"route":{"cluster":"httpbin"},"match":{"prefix":"/"}}],"domains":["*"],"name":"local_service"}]}}}]}]}],"clusters":[{"tls_context":{"sni":"httpbin.org"},"lb_policy":"round_robin","type":"logical_dns","name":"httpbin","hosts":[{"socket_address":{"port_value":443,"address":"httpbin.org"}}],"connect_timeout":"0.25s"},{"hosts":[{"socket_address":{"address":"127.0.0.1","port_value":8099}}],"name":"web_service","connect_timeout":"0.25s","lb_policy":"round_robin","type":"static"},{"name":"ext_web_service","lb_policy":"round_robin","hosts":[{"socket_address":{"port_value":8086,"address":"127.0.0.1"}}],"connect_timeout":"0.25s","type":"static"}]},"admin":{"address":{"socket_address":{"address":"0.0.0.0","port_value":8001}},"access_log_path":"/dev/null"}})
 ```
 
This change seems to be quite recent, and the whole lib seems to have been built on top of version 2, so i would like to know if there are still any config errors or if the lib still does not support envoy v3 api.
