### ISSUE TITLE
`dispatch_http_call` always fails with BadArgument

### ISSUE THREAD

**Issue by mflorin** [proxy-wasm/proxy-wasm-rust-sdk#172]
Hello,

I'm trying to send an http call to a configured envoy cluster. The call fails with `BadArgument` every time.

```
    fn on_tick(&mut self) {
        let result = self.dispatch_http_call(
            "codex_updater",
            vec![
                (":host", "codex_updater"),
                (":method", "GET"),
                (":path", "/update"),
            ],
            None,
            vec![],
            Duration::from_secs(60),
        );

        match result {
            Ok(_) => {
                self.log("call dispatched to codex updater");
            },
            Err(status) => {
                self.error(format!("Error dispatching call to updater service: {:?}", status).as_str())
            }
        }
    }
```

The envoy cluster configuration looks like this:

```yaml
static_resources:
...
  clusters:
    - name: codex_updater
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: codex_updater
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: codex_updater
                  port_value: 9001


```
