### ISSUE TITLE
setting :authority in initial_metadata creates two :authority values

### ISSUE THREAD

**Issue by collinlee** [proxy-wasm/proxy-wasm-rust-sdk#199]
When I attempt to set the [initial_metadata](https://docs.rs/proxy-wasm/latest/proxy_wasm/hostcalls/fn.dispatch_grpc_call.html) value as a vector in dispatch_grpc_call like so
```

dispatch_grpc_call(
                    "upstream-cluster",
                    "test.Service",
                    "testMethod",
                    vec![
                        (":scheme", "https".as_bytes()),
                        (":authority", "foo.aws.foobar.cl".as_bytes())
                    ],
                    Some(request.write_to_bytes().unwrap().as_slice()),
                    Duration::from_secs(2),
)
```

I see in the Envoy logs that the headers sent are

`':authority', 'foo.aws.foobar.cl'
`

Is there a way that :authority can only be set to foo.aws.foobar.cl?

**Comment by PiotrSikora** [comment]
gRPC's initial metadata is supplemental metadata that's encoded as HTTP headers, but those shouldn't be used as HTTP headers, and you cannot use it to override HTTP headers.

Having said that, it looks that Envoy implementation has a bug that allows setting two `:authority` values, which it concatenates.

Could you open issue there? Thanks! cc @mpwarres

**Comment by PiotrSikora** [comment]
Also, answering your original question, I think you should be able to configure `:authority` in `upstream-cluster's` configuration in Envoy using [the Endpoint's `hostname` field](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#config-endpoint-v3-endpoint).

**Comment by collinlee** [comment]
I've tried to see if in the cluster definition under load_assignment setting hostname in endpoint as you mentioned, but it doesn't seem to use that value in the authority header

```
          load_assignment:
            cluster_name: upstream-cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      hostname: foo.aws.foobar.cl
                      address:
                        socket_address:
                          address: foo.aws.foobar.cl
                          port_value: 80
```
