### ISSUE TITLE
Correct usage of `dispatch_http_call` 

### ISSUE THREAD

**Issue by kanishkarj** [proxy-wasm/proxy-wasm-rust-sdk#8]
Hi! I am trying to get an TCP filter to make http requests to another service.  As far as I understand that's what `dispatch_http_call` does right? I have written the following code and it doesn't seem to work. 

```rust

#[no_mangle]
pub fn _start() {
    proxy_wasm::set_stream_context(|context_id, root_context_id| -> Box<dyn StreamContext> {
        Box::new(TCPFilter::new())
    });
}

struct TCPFilter {}

impl Context for TCPFilter {
    fn on_http_call_response(&mut self,_token_id: u32,_num_headers: usize,_body_size: usize,_num_trailers: usize) {
        proxy_wasm::hostcalls::log(LogLevel::Debug, "Response recieved!");
    }
}

impl TCPFilter {
    fn new() -> Self {
        return Self {
        }
    }
}

impl StreamContext for TCPFilter {
    fn on_downstream_data(&mut self, _data_size: usize, _end_of_stream: bool) -> Action {
        Action::Continue
    }
    fn on_upstream_data(&mut self, _data_size: usize, _end_of_stream: bool) -> Action {
        Action::Continue
    }
    fn on_downstream_close(&mut self, _peer_type: PeerType) {
        
    }
    fn on_upstream_close(&mut self, _peer_type: PeerType) {
        const url: &str = "https://httpbin.org/post";
        let headers: Vec<(&str, &str)> = vec![];
        let trailers: Vec<(&str, &str)> = vec![];
        let timeout: Duration = Duration::new(1, 10);
        let x = self.dispatch_http_call(url, headers, None, trailers, timeout);
        proxy_wasm::hostcalls::log(LogLevel::Debug, &format!("Status : {:?}", x).as_str());   
    }
}

impl RootContext for TCPFilter {}
```

The Error from the logs : 
```sh
Status : Err(BadArgument)
```

My `envoy.yaml` : 

```yaml
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.wasm
        config:
          config:
            name: "tcp_filter"
            root_id: "tcp_filter"
            vm_config:
              runtime: "envoy.wasm.runtime.v8"
              code:
                local:
                  filename: "/etc/tcp_filter.wasm"
              allow_precompiled: true
      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress_tcp
          cluster: web_service
  - name: staticreply
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 8099
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: "example body\n"
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: web_service
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: web_service
        port_value: 5678
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

I'm assuming the way I am calling `dispatch_http_call` the wrong way. could someone help me out on this? 

Thanks

**Comment by kanishkarj** [comment]
I tried running `examples/http_auth_random.rs` and it doesn't seem to work either. any details will be appreciated.

**Comment by kanishkarj** [comment]
@PiotrSikora Any help on how to use `dispatch_http_call` would be really appreciated. Also, does it allow you to make calls to external services?

**Comment by nathanwilson** [comment]
Hello! I have been investigating the usage of this as well. I have not been able to get a call to an external service working, but I have managed to get something to run.

Following a read of the ABI docs, the variable you have as `const url: &str = "https://httpbin.org/post";` needs to match an "upstream" service. In the case of your `envoy.yaml`,  the cluster with the name `web_service` should work (`const url: &str = "web_service";`). However my understanding is then that you can only make a call to that upstream service.
(What "upstream" and "downstream" mean are defined here - https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT#tcpudpquic-stream-l4-extensions )


I have not yet managed to get a call to an external site working. If you find anything let me know! I don't have that much knowledge of envoy and hope I am missing something outside of the wasm portion of it.

**Comment by PiotrSikora** [comment]
Apologies for the late reply! What @nathanwilson just said is correct.

If you look at the [`dispatch_http_call`](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/3ebf309fd72d2545f3909d2adc13b2450567057e/src/traits.rs#L61) definition, you'll notice that the first argument is `upstream`, not `url`, and it has to match the name of the configured upstream in the proxy.

Following [http_auth_random example](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/3ebf309fd72d2545f3909d2adc13b2450567057e/examples/http_auth_random.rs#L30), your call should look like this:
```
self.dispatch_http_call(
    "httpbin",
    vec![
        (":method", "POST"),
        (":path", "/post"),
        (":authority", "httpbin.org"),
    ],
    None,
    vec![],
    Duration::from_secs(10),
)
.unwrap();
```
and you should have `httpbin` upstream defined in your configuration. Assuming that you're using Envoy or Istio, this would look like this:
```
clusters:
- name: httpbin
  connect_timeout: 5s
  type: LOGICAL_DNS
  dns_lookup_family: V4_ONLY
  lb_policy: ROUND_ROBIN
  hosts:
  - socket_address:
      protocol: TCP
      address: httpbin.org
      port_value: 443
    tls_context:
      sni: "httpbin.org"
```
Note that requirement to configure route in the proxy is a security feature, and it's unlikely that we'll allow Proxy-Wasm modules to make requests to destinations that are not configured by the proxy administrator.
