### ISSUE TITLE
RBAC integration

### ISSUE THREAD

**Issue by Gsantomaggio** [proxy-wasm/proxy-wasm-rust-sdk#81]
Hi all,
I'd need to integrate my network filter with RBAC.
I saw that standard filters use [`setDynamicMetadata`](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/postgres_proxy/postgres_filter.cc#L186) to emit the metadata. 

I am looking for something similar in the SDK, is that possible? 

Thank you for time.

**Comment by PiotrSikora** [comment]
It's not clear to me what kind of integration do you mean, but you can set filter metadata using `set_property`, e.g.
```
self.set_property(vec!["metadata", "filter_metadata", "envoy.filters.network.rbac", "something"], Some("value"));
```

**Comment by Gsantomaggio** [comment]
Thank you @PiotrSikora 

I'd need to implement something very similar to https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/mysql_proxy_filter#dynamic-metadata

**Comment by Gsantomaggio** [comment]
basically, I am looking for https://www.envoyproxy.io/docs/envoy/latest/configuration/advanced/well_known_dynamic_metadata

I will figure out how to that using `self.set_property(`

**Comment by Gsantomaggio** [comment]
Hi @PiotrSikora 
I changed the issue name hope it is more clear. 
What I am looking for is how to emit [dynamic metadata](https://www.envoyproxy.io/docs/envoy/latest/configuration/advanced/well_known_dynamic_metadata) so in this way, I can integrate my filter with RBAC as [MySQL filter does](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/mysql_proxy_filter#dynamic-metadata).

I think that your [comment](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/issues/81#issuecomment-780851819)  is about setting the proxy properties.

For the documentation:
```
setDynamicMetadata routine in the StreamInfo interface on a Connection
```
I am wondering if it is possible with the Rust SDK.

Hope it is more clear.
Thank you for your time

**Comment by yuval-k** [comment]
hi @PiotrSikora , from looking at the code, I can see how to fetch dynamic metadata with getProperty, but it's hard to see how [Context::setProperty](https://github.com/envoyproxy/envoy/blob/1d1b708c7bf6efa02c41d9ce22cbf1e4a1aeec2c/source/extensions/common/wasm/context.cc#L1123) sets dynamic metadata.

If I'm understanding the code correctly, setProperty can only set `filterState` and things that were registered using `declareProperty`?

**Comment by Gsantomaggio** [comment]
I changed the envoy [proxy wasm context.cc](https://github.com/envoyproxy/envoy/blob/1d1b708c7bf6efa02c41d9ce22cbf1e4a1aeec2c/source/extensions/common/wasm/context.cc#L1123) **just for test**

In this way (Thanks to @yuval-k to pointed me on it):
```cpp
WasmResult Context::setProperty(absl::string_view path, absl::string_view value) {
  auto* stream_info = getRequestStreamInfo();
  if (!stream_info) {
    return WasmResult::NotFound;
  }
  // ENVOY_LOG(debug, "***** setProperty wasm path:{}  value:{}", path, value);
  ProtobufWkt::Struct metadata_val;
  auto& fields_a = *metadata_val.mutable_fields();
  std::string v1;
  absl::StrAppend(&v1, value);
  fields_a[v1].set_bool_value(true);
  std::string key3;
  absl::StrAppend(&key3, path);
  stream_info->setDynamicMetadata(key3, metadata_val);
```
Rust code:
```rust
self.set_property(vec!["my.filters.network.network"],
                              Some("myitem".as_ref()));
```

And actually the filter works:

```
[2021-02-20 16:45:17.749][7215663][debug][rbac] [source/extensions/filters/network/rbac/rbac_filter.cc:45] checking connection: requestedServerName: , sourceIP: 127.0.0.1:54608, directRemoteIP: 127.0.0.1:54608,remoteIP: 127.0.0.1:54608, localAddress: 127.0.0.1:5673, ssl: none, 
dynamicMetadata: filter_metadata {
  key: "my.filters.network.network"
  value {
    fields {
      key: "myitem"
      value {
        bool_value: true
      }
    }
  }
}
```
 and also the RBAC works:
```
[2021-02-19 20:02:20.480][6826232][debug][rbac] [source/extensions/filters/network/rbac/rbac_filter.cc:125]
enforced denied, matched policy myitem-policy
```

envoy conf:
```yaml
filter_chains:
    - filters:
        - name: envoy.filters.network.wasm
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
            config:
              configuration: {"@type":"type.googleapis.com/google.protobuf.StringValue",
                              "value":""}
              name: "my.filters.network.network"
              root_id: "my.filters.network.network"
              vm_config:
                vm_id: "my.filters.network.network"
                runtime: envoy.wasm.runtime.v8
                code: {"local":{"filename":"wasm32-unknown-unknown/release/my_network_filter.wasm"}}
                allow_precompiled: true
        - name: envoy.filters.network.rbac
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
            stat_prefix: rbac
            rules:
              action: DENY
              policies:
                "myqueue-policy":
                  permissions:
                    - metadata:
                        filter: my.filters.network.network
                        path:
                          - key: myqueue1
                        value:
                           bool_match: true
```


`setDynamicMetadata` seems to be a missing feature on envoy mainstream. I was thinking of to open an issue on [envoy](https://github.com/envoyproxy/envoy)
