### ISSUE TITLE
How to pass configuration to WASM filter

### ISSUE THREAD

**Issue by pranav-bhatt** [proxy-wasm/proxy-wasm-rust-sdk#89]
Hi! I'm running Istio, and have been working on rust filters. The EnvoyFilter yaml I'm using looks like this, where the configuration value inside vmConfig is a base64 encoded json:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: imagehub-filter
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND # will match inbound listeners in all sidecars
      proxy:
        proxyVersion: '^1\.9.*'
      listener:
        portNumber: 9091
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filter.http.wasm
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: "rate_limit_filter"
              root_id: "rate_limit_filter"
              vmConfig:
                code:
                  local:
                    filename: "/var/lib/imagehub/filter.wasm"
                configuration: 
                  '@type': type.googleapis.com/google.protobuf.StringValue
                  value: "WwogIHsKICAgICJuYW1lIjogIi9wdWxsIiwKICAgICJydWxlIjp7CiAgICAgICJydWxlVHlwZSI6ICJyYXRlLWxpbWl0ZXIiLAogICAgICAicGFyYW1ldGVycyI6WwogICAgICAgIHsiaWRlbnRpZmllciI6ICJFbnRlcnByaXNlIiwgImxpbWl0IjogMTAwMH0sCiAgICAgICAgeyJpZGVudGlmaWVyIjogIlRlYW0iLCAibGltaXQiOiAxMDB9LAogICAgICAgIHsiaWRlbnRpZmllciI6ICJQZXJzb25hbCIsICJsaW1pdCI6IDEwfQogICAgICBdCiAgICB9CiAgfSwKICB7CiAgICAibmFtZSI6ICIvYXV0aCIsCiAgICAicnVsZSI6ewogICAgICAicnVsZVR5cGUiOiAibm9uZSIKICAgIH0KICB9LAogIHsKICAgICJuYW1lIjogIi9zaWdudXAiLAogICAgInJ1bGUiOnsKICAgICAgInJ1bGVUeXBlIjogIm5vbmUiCiAgICB9CiAgfSwKICB7CiAgICAibmFtZSI6ICIvdXBncmFkZSIsCiAgICAicnVsZSI6ewogICAgICAicnVsZVR5cGUiOiAibm9uZSIKICAgIH0KICB9Cl0="
                runtime: envoy.wasm.runtime.v8
                vmId: rate_limit_filter
                allow_precompiled: true
  workloadSelector:
    labels:
      app: api
      version: v1
```

My filter code basically centers around the UpstreamCall struct. Lines 120-127 is where the struct is getting populated using the `on_configure()` call. Ideally this should get the configuration value, parse it into base64. From the debugging I've done, it seems like `on_configure()` is never called. Any tips on what I could be doing wrong?
```rust
mod rate_limiter;
mod yaml_parse;

use proxy_wasm::traits::*;
use proxy_wasm::types::*;
use rate_limiter::RateLimiter;
use serde::Deserialize;
use yaml_parse::JsonPath;

use std::time::SystemTime;

#[no_mangle]
pub fn _start() {
    proxy_wasm::set_log_level(LogLevel::Info);
    proxy_wasm::set_http_context(|_context_id, _root_context_id| -> Box<dyn HttpContext> {
        Box::new(UpstreamCall::new())
    });
}

#[derive(Debug)]
struct UpstreamCall {
    data: Vec<JsonPath>,
    paths: Vec<String>,
}

impl UpstreamCall {
    fn new() -> Self {
        Self {
            data: Vec::new(),
            paths: Vec::new(),
        }
    }

    fn get_paths(json: &Vec<JsonPath>) -> Vec<String> {
        let mut allowed_paths: Vec<String> = json.iter().map(|e| e.name.clone()).collect();
        allowed_paths.sort();
        allowed_paths
    }
}

//static ALLOWED_PATHS: [&str; 4] = ["/auth", "/signup", "/upgrade", "/pull"];
static CORS_HEADERS: [(&str, &str); 5] = [
    ("Powered-By", "proxy-wasm"),
    ("Access-Control-Allow-Origin", "*"),
    ("Access-Control-Allow-Methods", "*"),
    ("Access-Control-Allow-Headers", "*"),
    ("Access-Control-Max-Age", "3600"),
];

#[derive(Deserialize, Debug)]
struct Data {
    username: String,
    plan: String,
}

impl HttpContext for UpstreamCall {
    fn on_http_request_headers(&mut self, _num_headers: usize) -> Action {
        if let Some(method) = self.get_http_request_header(":method") {
            if method == "OPTIONS" {
                self.send_http_response(204, CORS_HEADERS.to_vec(), None);
                return Action::Pause;
            }
        }
        /*
        if let Some(path) = self.get_http_request_header(":path") {
            if ALLOWED_PATHS.binary_search(&path.as_str()).is_ok() {
                return Action::Continue;
            }
        }
        */
        if let Some(path) = self.get_http_request_header(":path") {
            if self.paths.binary_search(&path).is_ok() {
                return Action::Continue;
            }
        }
        if let Some(header) = self.get_http_request_header("Authorization") {
            if let Ok(token) = base64::decode(header) {
                let obj: Data = serde_json::from_slice(&token).unwrap();
                proxy_wasm::hostcalls::log(LogLevel::Debug, format!("Obj {:?}", obj).as_str()).ok();
                let curr = self.get_current_time();
                let tm = curr.duration_since(SystemTime::UNIX_EPOCH).unwrap();
                let mn = (tm.as_secs() / 60) % 60;
                let _sc = tm.as_secs() % 60;
                let mut rl = RateLimiter::get(obj.username, obj.plan);

                let mut headers = CORS_HEADERS.to_vec();
                let count: String;

                if !rl.update(mn as i32) {
                    count = rl.count.to_string();
                    headers.append(&mut vec![("x-rate-limit", &count), ("x-app-user", &rl.key)]);
                    self.send_http_response(429, headers, Some(b"Limit exceeded.\n"));
                    rl.set();
                    return Action::Pause;
                }
                proxy_wasm::hostcalls::log(LogLevel::Debug, format!("Obj {:?}", &rl).as_str()).ok();
                count = rl.count.to_string();
                rl.set();
                headers.append(&mut vec![("x-rate-limit", &count), ("x-app-user", &rl.key)]);
                self.send_http_response(200, headers, Some(b"All Good!\n"));
                return Action::Continue;
            }
        }
        self.send_http_response(401, CORS_HEADERS.to_vec(), Some(b"Unauthorized\n"));
        Action::Pause
    }

    fn on_http_response_headers(&mut self, _num_headers: usize) -> Action {
        let json_test = format!("{:?}", self.paths);
        self.set_http_response_header("x-app-serving", Some("rate-limit-filter"));
        self.set_http_response_header("json_test", Some(json_test.as_str()));
        proxy_wasm::hostcalls::log(LogLevel::Debug, format!("RESPONDING").as_str()).ok();
        Action::Continue
    }
}

impl Context for UpstreamCall {}
impl RootContext for UpstreamCall {
    //TODO: Revisit this once the read only feature is released in Istio 1.10
    fn on_configure(&mut self, _: usize) -> bool {
        if let Some(config_bytes) = self.get_configuration() {
            let config_b64 = base64::decode(config_bytes).unwrap();
            self.data = serde_json::from_slice(&config_b64).unwrap();
            self.paths = UpstreamCall::get_paths(&self.data);
        }
        true
    }
}

```
